name: renting_mobile_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  font_awesome_flutter: ^10.4.0
  flutter_svg: ^2.0.16
  get: ^4.6.6
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-Regular.ttf
          weight: 700
  assets:
    - assets/images/items/drill.jpg
    - assets/images/items/bike.png
    - assets/images/items/electronics.png
    - assets/images/items/furniture.png
    - assets/images/items/google_pixel_tablet.png
    - assets/images/items/sports.png
    - assets/images/items/stainless_pot.png
    - assets/images/items/tools.png
    - assets/images/profiles/profile.jpg
    - assets/images/profiles/profile_rating1.jpg
    - assets/images/profiles/profile_rating2.jpg
    - assets/images/profiles/profile_rating3.jpg
    - assets/images/profiles/profile_rating4.jpg
    - assets/icons/chat.svg
    - assets/icons/map.svg
    - assets/icons/stars.svg
    
    